/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class stone_com_ndkdemo_NativeAdd */

#ifndef _Included_stone_com_ndkdemo_NativeAdd
#define _Included_stone_com_ndkdemo_NativeAdd
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     stone_com_ndkdemo_NativeAdd
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_stone_com_ndkdemo_NativeAdd_getStringFromNative
  (JNIEnv *, jobject);

/*
 * Class:     stone_com_ndkdemo_NativeAdd
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_stone_com_ndkdemo_NativeAdd_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
